---
- name: Install apps package (apt, yum, etc..)
  become: yes
  package: name={{ item }} state=latest
  with_items:
    - git
    - python-pip

- name: Install pip packages 
  # become: yes
  pip: name={{ item }} state=latest
  with_items:
    - robotframework
    - robotframework-sshlibrary
    - robotframework-selenium2library
