db:
  image: mysql
  volumes:
    - ~/Documents/Developer/alura-docker/blog-alura/database/:/var/lib/mysql/
  environment:
    - MYSQL_ROOT_PASSWORD=123456

blog:
  image: wordpress
  environment:
    - WORDPRESS_DB_PASSWORD=123456
  links:
    - db:mysql
  ports:
    - 80:80