---

- name: Install apps package (apt, yum, etc..)
  package: name={{ item }} state=present
  with_items:
    - git
    - python-pip
    - build-essential
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install apps package (apt, yum, etc..) CentOS
  package: name={{ item }} state=present
  with_items:
    - git
    - epel-release
    - python-pip
    - "@Development tools"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora'

- name: Install pip packages 
  become: no # Ubuntu gives an error with become:yes if already in sudoer context
  pip: 
    name={{ item }} 
    state=present
    extra_args=--user
  with_items:
    - robotframework
    - robotframework-sshlibrary
    - robotframework-seleniumlibrary
