---

- name: Install apps package (apt, yum, etc..)
  become: True
  package: name={{ item }} state=present
  with_items:
    - git
    - python-pip

- name: Install pip packages 
  become: True
  pip: name={{ item }} state=present
  with_items:
    - robotframework
    - robotframework-sshlibrary
    - robotframework-selenium2library
